
# reproducibility
deterministic: False
random_seed: 42
dirpath: "/content/drive/MyDrive/checkpoints"
# training

pl_trainer:
  _target_: pytorch_lightning.Trainer
  fast_dev_run: False # Enable this for debug purposes
  precision: 32
  tpu_cores: 8
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 10.0
  min_epochs: 1

monitor_metric: 'val_loss'
monitor_metric_mode: 'min'

early_stopping:
  patience: 42
  verbose: False

model_checkpoints:
  save_top_k: 2
  verbose: True
#  every_n_train_steps: 10000
  every_n_val_epochs: 1