# @package _group_
_target_: src.pl_modules.model.PatchNet
yolo_version: 'yolov3'
patch_size: 400
alpha: 10
init_patch: 'random'
log_interval: 100
patch_transforms:
  degrees:
    - -10
    - 10
  translate:
    - 0.25
    - 0.25
  scale:
    - 0.8
    - 1.2
  brightness:
    0.2
  portion:
    1