
_target_: src.pl_modules.model.PatchNet
yolo_version: 'yolov4-tiny'
alpha: 0.1
init_patch: 'gray'
log_interval: 100
patch_transformer:
  _target_: src.pl_modules.patch.PatchTransformer
  patch_size: 400
  image_size: 416
  #  degrees:
  #    - -10
  #    - 10
  #  translate:
  #    - 0.25
  #    - 0.25
  #  scale:
  #    - 0.8
  #    - 1.2
  brightness:
    0.2
  contrast:
    0
  #    0.2
  saturation:
    0
  hue:
    0
  #    0.2
  portion:
    0.3
pred_extractor:
  _target_: src.pl_modules.yolo.PredExtractor
  target_class: 'person'


