# @package _group_
_target_: src.pl_modules.model.PatchNet
yolo_version: 'yolov3-tiny'
patch_size: 400
alpha: 1
init_patch: 'gray'
log_interval: 100
patch_transforms:
  degrees:
    - -10
    - 10
  translate:
    - 0.25
    - 0.25
  scale:
    - 0.8
    - 1.2
  brightness:
    0.2
  contrast:
    0
  hue:
    0
  saturation:
    0
  portion:
    0.3