
_target_: src.pl_modules.model.PatchNet
yolo_version: 'yolov4-tiny'
alpha: 0.1
init_patch: 'gray'
log_interval: 100
patch_size: 400
thresh_hold: 0.5
patch_transformer:
  _target_: src.pl_modules.patch.PatchTransformer
  image_size: 416
  portion: 1
  patch_transforms:
    color_jitter:
      _target_: torchvision.transforms.ColorJitter
      brightness: 0.2
      contrast: 0
      saturation: 0
      hue: 0
    pad:
      _target_: torchvision.transforms.Pad
      padding: 40
    affine:
      _target_: torchvision.transforms.RandomAffine
      degrees:
        - -10
        - 10
      translate:
        - 0.25
        - 0.25
      scale:
        - 0.8
        - 1.2
      interpolation: "${get_class:transforms.InterpolationMode.NEAREST}"
    perspective:
      _target_: torchvision.transforms.RandomPerspective
      interpolation: "${get_class:transforms.InterpolationMode.NEAREST}"
pred_extractor:
  _target_: src.pl_modules.yolo.PredExtractor
  target_class: 'person'


